# Generated by Django 5.0.4 on 2024-05-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customer_company_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
