# Generated by Django 5.0.4 on 2024-05-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_customer_first_name_remove_customer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='town',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
