# Generated by Django 4.2.11 on 2024-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_signed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
